// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDdNhGrLyjIgxgQkV_9aMOxuQ9oPVXXU',
    appId: '1:503620366616:web:35c84e3318e97ccf976e6d',
    messagingSenderId: '503620366616',
    projectId: 'flutter-projecteiei',
    authDomain: 'flutter-projecteiei.firebaseapp.com',
    storageBucket: 'flutter-projecteiei.appspot.com',
    measurementId: 'G-SFW7J3M67E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgRDKQiLJ6g9jboptBeWMebGqvLjLz1Q',
    appId: '1:503620366616:android:ceea343c5680df57976e6d',
    messagingSenderId: '503620366616',
    projectId: 'flutter-projecteiei',
    storageBucket: 'flutter-projecteiei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWv66w7h6cKrqQyvJbolpaC35JdvBOHo',
    appId: '1:503620366616:ios:1155ced169394a19976e6d',
    messagingSenderId: '503620366616',
    projectId: 'flutter-projecteiei',
    storageBucket: 'flutter-projecteiei.appspot.com',
    iosClientId: '503620366616-2bqaur9apiuvjrq3078eug82v24utgpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjecteiei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgWv66w7h6cKrqQyvJbolpaC35JdvBOHo',
    appId: '1:503620366616:ios:1155ced169394a19976e6d',
    messagingSenderId: '503620366616',
    projectId: 'flutter-projecteiei',
    storageBucket: 'flutter-projecteiei.appspot.com',
    iosClientId: '503620366616-2bqaur9apiuvjrq3078eug82v24utgpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjecteiei',
  );
}
